/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    tutorials: Tutorial;
    tags: Tag;
    feedbacks: Feedback;
    'support-settings': SupportSetting;
    'user-informations': UserInformation;
    permissions: Permission;
    'user-gamification': UserGamification;
    'user-inventory': UserInventory;
    'user-currency': UserCurrency;
    quests: Quest;
    'user-quests': UserQuest;
    achievements: Achievement;
    'user-achievement-progress': UserAchievementProgress;
    challenges: Challenge;
    userChallengeProgression: UserChallengeProgression;
    'challenge-submissions': ChallengeSubmission;
    notifications: Notification;
    'challenge-categories': ChallengeCategory;
    'user-following-informations': UserFollowingInformation;
    items: Item;
    'user-items': UserItem;
    'active-effects': ActiveEffect;
    'marketplace-items': MarketplaceItem;
    divisions: Division;
    'experience-logs': ExperienceLog;
    'weekly-division-leaderboards': WeeklyDivisionLeaderboard;
    'weekly-leaderboard-members': WeeklyLeaderboardMember;
    skills: Skill;
    concepts: Concept;
    userConceptProgressions: UserConceptProgression;
    'user-overall-skill-progressions': UserOverallSkillProgression;
    'challenge-concept-outcomes': ChallengeConceptOutcome;
    conceptGroups: ConceptGroup;
    courses: Course;
    'learning-paths': LearningPath;
    chapters: Chapter;
    courseParts: CoursePart;
    coursePartUserProgression: CoursePartUserProgression;
    coursePartSubmissions: CoursePartSubmission;
    userChapterProgress: UserChapterProgress;
    coursePartFeedback: CoursePartFeedback;
    'user-onboarding': UserOnboarding;
    'blog-articles': BlogArticle;
    userChallengeEngagement: UserChallengeEngagement;
    userChallengeCompletionStatus: UserChallengeCompletionStatus;
    userChallengeCode: UserChallengeCode;
    'daily-login-entries': DailyLoginEntry;
    'challenge-streaks': ChallengeStreak;
    'challenge-ai-chats': ChallengeAiChat;
    'user-ai-usage': UserAiUsage;
    'user-ai-credits': UserAiCredit;
    'chat-histories': ChatHistory;
    'challenge-rating': ChallengeRating;
    'challenges-ratings': ChallengesRating;
    'challenge-engagement': ChallengeEngagement;
    'challenges-engagement': ChallengesEngagement;
    exercices: Exercice;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tutorials: TutorialsSelect<false> | TutorialsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    'support-settings': SupportSettingsSelect<false> | SupportSettingsSelect<true>;
    'user-informations': UserInformationsSelect<false> | UserInformationsSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'user-gamification': UserGamificationSelect<false> | UserGamificationSelect<true>;
    'user-inventory': UserInventorySelect<false> | UserInventorySelect<true>;
    'user-currency': UserCurrencySelect<false> | UserCurrencySelect<true>;
    quests: QuestsSelect<false> | QuestsSelect<true>;
    'user-quests': UserQuestsSelect<false> | UserQuestsSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    'user-achievement-progress': UserAchievementProgressSelect<false> | UserAchievementProgressSelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    userChallengeProgression: UserChallengeProgressionSelect<false> | UserChallengeProgressionSelect<true>;
    'challenge-submissions': ChallengeSubmissionsSelect<false> | ChallengeSubmissionsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'challenge-categories': ChallengeCategoriesSelect<false> | ChallengeCategoriesSelect<true>;
    'user-following-informations': UserFollowingInformationsSelect<false> | UserFollowingInformationsSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    'user-items': UserItemsSelect<false> | UserItemsSelect<true>;
    'active-effects': ActiveEffectsSelect<false> | ActiveEffectsSelect<true>;
    'marketplace-items': MarketplaceItemsSelect<false> | MarketplaceItemsSelect<true>;
    divisions: DivisionsSelect<false> | DivisionsSelect<true>;
    'experience-logs': ExperienceLogsSelect<false> | ExperienceLogsSelect<true>;
    'weekly-division-leaderboards': WeeklyDivisionLeaderboardsSelect<false> | WeeklyDivisionLeaderboardsSelect<true>;
    'weekly-leaderboard-members': WeeklyLeaderboardMembersSelect<false> | WeeklyLeaderboardMembersSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    concepts: ConceptsSelect<false> | ConceptsSelect<true>;
    userConceptProgressions: UserConceptProgressionsSelect<false> | UserConceptProgressionsSelect<true>;
    'user-overall-skill-progressions': UserOverallSkillProgressionsSelect<false> | UserOverallSkillProgressionsSelect<true>;
    'challenge-concept-outcomes': ChallengeConceptOutcomesSelect<false> | ChallengeConceptOutcomesSelect<true>;
    conceptGroups: ConceptGroupsSelect<false> | ConceptGroupsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'learning-paths': LearningPathsSelect<false> | LearningPathsSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    courseParts: CoursePartsSelect<false> | CoursePartsSelect<true>;
    coursePartUserProgression: CoursePartUserProgressionSelect<false> | CoursePartUserProgressionSelect<true>;
    coursePartSubmissions: CoursePartSubmissionsSelect<false> | CoursePartSubmissionsSelect<true>;
    userChapterProgress: UserChapterProgressSelect<false> | UserChapterProgressSelect<true>;
    coursePartFeedback: CoursePartFeedbackSelect<false> | CoursePartFeedbackSelect<true>;
    'user-onboarding': UserOnboardingSelect<false> | UserOnboardingSelect<true>;
    'blog-articles': BlogArticlesSelect<false> | BlogArticlesSelect<true>;
    userChallengeEngagement: UserChallengeEngagementSelect<false> | UserChallengeEngagementSelect<true>;
    userChallengeCompletionStatus: UserChallengeCompletionStatusSelect<false> | UserChallengeCompletionStatusSelect<true>;
    userChallengeCode: UserChallengeCodeSelect<false> | UserChallengeCodeSelect<true>;
    'daily-login-entries': DailyLoginEntriesSelect<false> | DailyLoginEntriesSelect<true>;
    'challenge-streaks': ChallengeStreaksSelect<false> | ChallengeStreaksSelect<true>;
    'challenge-ai-chats': ChallengeAiChatsSelect<false> | ChallengeAiChatsSelect<true>;
    'user-ai-usage': UserAiUsageSelect<false> | UserAiUsageSelect<true>;
    'user-ai-credits': UserAiCreditsSelect<false> | UserAiCreditsSelect<true>;
    'chat-histories': ChatHistoriesSelect<false> | ChatHistoriesSelect<true>;
    'challenge-rating': ChallengeRatingSelect<false> | ChallengeRatingSelect<true>;
    'challenges-ratings': ChallengesRatingsSelect<false> | ChallengesRatingsSelect<true>;
    'challenge-engagement': ChallengeEngagementSelect<false> | ChallengeEngagementSelect<true>;
    'challenges-engagement': ChallengesEngagementSelect<false> | ChallengesEngagementSelect<true>;
    exercices: ExercicesSelect<false> | ExercicesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-friendly identifier for this article. Will be used in the URL.
   */
  slug: string;
  subtitle?: string | null;
  content: string;
  /**
   * Information for search engine optimization (SEO) of the article in the main language (English)
   */
  seo?: {
    /**
     * Optimized title for search engines (if different from the main title)
     */
    title?: string | null;
    /**
     * Short description for search results (150-160 characters recommended)
     */
    description?: string | null;
    /**
     * Relevant keywords for SEO
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Article visibility (independent from the draft/publish system)
   */
  articleStatus: 'active' | 'archived';
  /**
   * Difficulty level of the article
   */
  difficultyLevel: 'beginner' | 'intermediate' | 'advanced';
  author: number | User;
  /**
   * Concepts related to this article (e.g., "python", "object-oriented")
   */
  tags?: (number | Tag)[] | null;
  /**
   * Engagement metrics for this article (normally updated automatically)
   */
  analytics?: {
    /**
     * Total number of article views
     */
    views?: number | null;
    /**
     * Number of distinct visitors who viewed the article
     */
    uniqueViews?: number | null;
    /**
     * Number of times the article was viewed from a recommendation
     */
    recommendationClicks?: number | null;
    /**
     * Average time spent on the article in seconds
     */
    averageTimeSpent?: number | null;
    /**
     * Percentage of users who leave after viewing only this article
     */
    bounceRate?: number | null;
    /**
     * Total number of ratings received for this article
     */
    ratingCount?: number | null;
    /**
     * Sum of all ratings (scale of 1 to 5) - allows calculating the average
     */
    ratingSum?: number | null;
  };
  /**
   * Add translations for this article (the default language is English)
   */
  translations?:
    | {
        language: 'fr' | 'es';
        title: string;
        subtitle?: string | null;
        content: string;
        translator?: (number | null) | User;
        /**
         * Information for search engine optimization (SEO) of this translation
         */
        seo?: {
          /**
           * Optimized title for search engines (if different from the translated title)
           */
          title?: string | null;
          /**
           * Short description for search results (150-160 characters recommended)
           */
          description?: string | null;
          /**
           * Relevant keywords for SEO in this language
           */
          keywords?:
            | {
                keyword?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Select articles that are related to this article
   */
  relatedArticles?: (number | Article)[] | null;
  /**
   * Articles that should be read before this one
   */
  prerequisites?: (number | Article)[] | null;
  /**
   * Recommended articles to read after this one
   */
  nextSteps?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  status: 'test' | 'public';
  usageCount: number;
  creatorId: string;
  lastUsedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials".
 */
export interface Tutorial {
  id: number;
  title: string;
  /**
   * URL-friendly identifier for this tutorial. Will be used in the URL.
   */
  slug: string;
  description?: string | null;
  /**
   * Tutorial visibility (independent from the draft/publish system)
   */
  tutorialStatus: 'active' | 'archived';
  /**
   * Sections of the tutorial, each containing a list of articles
   */
  sections: {
    title: string;
    description?: string | null;
    /**
     * Articles included in this section, in display order
     */
    articles: (number | Article)[];
    id?: string | null;
  }[];
  /**
   * Example sections for this tutorial, each grouping similar articles
   */
  exampleSections?:
    | {
        title: string;
        /**
         * Example articles included in this section
         */
        articles: (number | Article)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Reference article sections for this tutorial, organized by theme or category
   */
  referenceSections?:
    | {
        title: string;
        description?: string | null;
        /**
         * Reference articles included in this section
         */
        articles: (number | Article)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Add translations for the tutorial title (the default language is English)
   */
  translations?:
    | {
        language: 'fr' | 'es';
        title: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  message: string;
  /**
   * The slug of the article where the feedback was submitted
   */
  articleSlug?: string | null;
  /**
   * The slug of the tutorial where the feedback was submitted
   */
  tutorialSlug?: string | null;
  /**
   * IP address of the user who submitted the feedback (for rate limiting)
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-settings".
 */
export interface SupportSetting {
  id: number;
  /**
   * Name of the settings (should be "Support Settings")
   */
  name: string;
  /**
   * Current status of the support system
   */
  status: 'online' | 'maintenance' | 'offline';
  /**
   * Message to display when support is in maintenance mode
   */
  maintenanceMessage?: string | null;
  /**
   * Message to display when support is offline
   */
  offlineMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-informations".
 */
export interface UserInformation {
  id: number;
  userId: string;
  name?: string | null;
  avatar?: string | null;
  initials?: string | null;
  role: 'basic' | 'lite' | 'pro' | 'max' | 'admin';
  /**
   * Select permissions for this user
   */
  permissions?: (number | Permission)[] | null;
  preferences?: {
    notifications?: {
      friends?: boolean | null;
    };
    emails?: {
      marketing?: boolean | null;
      affiliates?: boolean | null;
    };
    theme?: ('light' | 'dark' | 'system') | null;
  };
  customerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Unique code used to identify this permission in the system
   */
  code: string;
  category?: ('content' | 'users' | 'system' | 'other') | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user level, experience, and division.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-gamification".
 */
export interface UserGamification {
  id: number;
  userId: string;
  currentLevel: number;
  currentExperience: number;
  totalExperience: number;
  lastLevelUpDate: string;
  division?: (number | null) | Division;
  /**
   * Number of times the user has replaced a daily quest today.
   */
  dailyQuestReplacementsUsed?: number | null;
  /**
   * The date the user last replaced a quest.
   */
  lastQuestReplacementDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions".
 */
export interface Division {
  id: number;
  name: string;
  /**
   * Optional: Minimum user level required to be initially placed in this division.
   */
  levelRequirement?: number | null;
  /**
   * Top X% of users in a weekly leaderboard group to be promoted.
   */
  promotionThreshold: number;
  /**
   * Bottom X% of users in a weekly leaderboard group to be demoted.
   */
  demotionThreshold: number;
  /**
   * Numerical order for divisions (e.g., 1 for Bronze, 2 for Silver). Lower numbers are lower ranks.
   */
  rankOrder?: number | null;
  /**
   * Define coin rewards based on final weekly rank ranges.
   */
  rewards?:
    | {
        /**
         * The starting rank for this reward tier.
         */
        rankStart: number;
        /**
         * The ending rank for this reward tier.
         */
        rankEnd: number;
        /**
         * The number of coins to award for this rank range.
         */
        coinAmount: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-inventory".
 */
export interface UserInventory {
  id: number;
  /**
   * The ID of the user this inventory belongs to
   */
  userId: string;
  /**
   * Items in the user's inventory
   */
  items?: {
    /**
     * List of items in the inventory
     */
    itemEntries?:
      | {
          /**
           * The type of the item
           */
          itemType: 'experience_boost' | 'streak_saver' | 'streak_recovery' | 'solution_viewer' | 'chest';
          /**
           * The specific variant of the item (e.g., "basic", "premium", "legendary")
           */
          itemVariant: 'basic' | 'premium' | 'legendary';
          /**
           * The quantity of this item
           */
          quantity: number;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Total number of items in the inventory
   */
  itemCount?: number | null;
  /**
   * When this inventory was last updated
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-currency".
 */
export interface UserCurrency {
  id: number;
  /**
   * The ID of the user who owns this currency
   */
  userId: string;
  /**
   * The amount of currency owned by the user
   */
  quantity: number;
  /**
   * History of currency transactions
   */
  transactionHistory?:
    | {
        timestamp: string;
        type: 'earn' | 'spend' | 'system';
        amount: number;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests".
 */
export interface Quest {
  id: number;
  title: string;
  type: 'experienceGained' | 'challengesCompleted' | 'increasedLevel';
  difficulty: 'easy' | 'medium' | 'hard';
  value: number;
  experience: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-quests".
 */
export interface UserQuest {
  id: number;
  userId: string;
  quest: number | Quest;
  currentProgression: number;
  isCompleted: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  /**
   * The title of the achievement
   */
  title: string;
  /**
   * The type of achievement that determines how progress is calculated
   */
  type:
    | 'experience_gained'
    | 'challenges_completed'
    | 'streak'
    | 'tutorials_completed'
    | 'quests_completed'
    | 'items_used'
    | 'coins_earned';
  /**
   * The icon identifier for this achievement
   */
  icon?: string | null;
  /**
   * The maximum number of tiers for this achievement (typically 4 for Bronze, Silver, Gold, Diamond)
   */
  maxTier: number;
  /**
   * The different tiers of the achievement
   */
  tiers: {
    /**
     * The name of the tier (Bronze, Silver, Gold, etc.)
     */
    name: 'bronze' | 'silver' | 'gold' | 'diamond' | 'platinum';
    /**
     * The description specific to this achievement tier
     */
    description: string;
    /**
     * The value to reach to obtain this achievement tier
     */
    threshold: number;
    /**
     * The number of coins given as a reward for this tier
     */
    rewardCoins: number;
    /**
     * The number of experience points given as a reward for this tier
     */
    rewardXp: number;
    /**
     * An optional item given as a reward for this tier.
     */
    rewardItem?: (number | null) | Item;
    id?: string | null;
  }[];
  /**
   * Optional: The achievement that follows this one in a sequence.
   */
  nextAchievement?: (number | null) | Achievement;
  /**
   * Indicates if this achievement is currently active in the system
   */
  isActive?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  /**
   * The name of the item
   */
  name: string;
  /**
   * A detailed description of what this item does
   */
  description: string;
  /**
   * The type of effect this item provides, or if it is a chest
   */
  type: 'xpBoost' | 'currencyBoost' | 'streakRestore' | 'unlockFeature' | 'chest';
  /**
   * How this item is activated and used
   */
  activationMode: 'consumableDuration' | 'consumableInstant' | 'passive';
  /**
   * Multiplier value for boost effects (e.g. 1.5 for 50% boost)
   */
  multiplier?: number | null;
  /**
   * Duration of the effect in seconds (only for consumable duration items)
   */
  duration?: number | null;
  /**
   * Whether this item provides its effect just by being owned
   */
  appliesPassively?: boolean | null;
  /**
   * Icon identifier for this item
   */
  icon?: string | null;
  /**
   * The rarity level of this item
   */
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
  /**
   * Define the rewards contained in this chest (coins, XP, and number of items per rarity).
   */
  chestRewards?: {
    minCoins: number;
    maxCoins: number;
    minXp: number;
    maxXp: number;
    commonItemsCount: number;
    rareItemsCount: number;
    epicItemsCount: number;
    legendaryItemsCount: number;
  };
  /**
   * Whether this item is currently available in the game
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user progress towards specific achievements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-achievement-progress".
 */
export interface UserAchievementProgress {
  id: number;
  /**
   * The Supabase UUID of the user.
   */
  userId: string;
  achievement: number | Achievement;
  /**
   * The current progress value towards the next tier threshold.
   */
  currentProgress: number;
  /**
   * The index of the highest achieved tier in the Achievement's tiers array (-1 if none).
   */
  currentTierIndex: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: number;
  /**
   * The title of the challenge
   */
  title: string;
  /**
   * URL-friendly identifier for this challenge. Will be used in the URL.
   */
  slug: string;
  /**
   * The difficulty level of the challenge
   */
  difficulty: 'very_easy' | 'easy' | 'medium' | 'hard' | 'horrible';
  /**
   * Experience points awarded for completing this challenge (calculated automatically)
   */
  baseExperience?: number | null;
  /**
   * Challenge description and problem statement
   */
  description: {
    /**
     * Problem statement and challenge description
     */
    statement: string;
    /**
     * Helpful hints for solving the challenge
     */
    hints?:
      | {
          content: string;
          id?: string | null;
        }[]
      | null;
    /**
     * List of related challenges
     */
    similarChallenges?:
      | {
          /**
           * Select a related challenge
           */
          challenge: number | Challenge;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The official solution for this challenge
   */
  officialSolution: {
    /**
     * The content of the official solution
     */
    statement: string;
  };
  /**
   * Different programming language versions of this challenge
   */
  codeVersions?:
    | {
        /**
         * Programming language for this version
         */
        language: string;
        /**
         * Initial code provided to users for this language
         */
        initialCode: string;
        /**
         * Test cases for validating solutions in this language
         */
        testCases?:
          | {
              /**
               * Input data for the test case
               */
              input: string;
              /**
               * Expected output for this test case
               */
              expectedOutput: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Indique si le challenge est en mode brouillon (draft)
   */
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeProgression".
 */
export interface UserChallengeProgression {
  id: number;
  /**
   * ID of the user
   */
  userId: string;
  /**
   * Related challenge
   */
  challenge: number | Challenge;
  /**
   * Whether the user has liked this challenge
   */
  hasLiked?: boolean | null;
  /**
   * Whether the user has disliked this challenge
   */
  hasDisliked?: boolean | null;
  /**
   * User rating for this challenge (1-5)
   */
  rating?: number | null;
  /**
   * Current completion status of the challenge
   */
  completionStatus: 'not_started' | 'in_progress' | 'completed';
  /**
   * Whether the solution has been unlocked by the user
   */
  isSolutionUnlocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-submissions".
 */
export interface ChallengeSubmission {
  id: number;
  /**
   * Type of submission result
   */
  submissionType: 'accepted' | 'runtimeError' | 'wrongAnswer' | 'timeLimitExceeded';
  /**
   * The challenge this submission is for
   */
  challenge: number | Challenge;
  /**
   * The user who made this submission
   */
  authorId: string;
  /**
   * Number of test cases passed
   */
  testsPassed: number;
  /**
   * Total number of test cases
   */
  testsTotal: number;
  code: {
    /**
     * Programming language used for the submission
     */
    language: string;
    /**
     * Source code of the submission
     */
    content: string;
  };
  /**
   * Error message for runtime error submissions
   */
  error?: string | null;
  /**
   * Last expected outputs before the error occurred
   */
  lastExpectedOutput?:
    | {
        output?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Input that caused the wrong answer
   */
  input?: string | null;
  /**
   * Actual output produced by the submission
   */
  output?: string | null;
  /**
   * Expected output for the given input
   */
  expectedOutput?: string | null;
  /**
   * When this submission was made
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  userId: string;
  content: string;
  importance: 'high' | 'medium' | 'low';
  type: 'system' | 'challenge' | 'achievement' | 'social';
  isRead?: boolean | null;
  /**
   * Optional URL or route for the notification action
   */
  actionUrl?: string | null;
  /**
   * Optional expiration date for the notification
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-categories".
 */
export interface ChallengeCategory {
  id: number;
  /**
   * The name of the challenge category
   */
  name: string;
  /**
   * A brief summary of the category that appears at the top of the page
   */
  summary?: string | null;
  /**
   * A detailed description of what this category covers
   */
  description: string;
  /**
   * URL-friendly identifier for this category
   */
  slug: string;
  /**
   * Whether this category is locked and unavailable to users
   */
  isLocked?: boolean | null;
  /**
   * Different parts/sections within this category
   */
  parts?:
    | {
        /**
         * Name of this part/section
         */
        name: string;
        /**
         * Description of what this part covers
         */
        description?: string | null;
        /**
         * Sequence of challenges in this part
         */
        challenges: (number | Challenge)[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User following relationships and blocked users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-following-informations".
 */
export interface UserFollowingInformation {
  id: number;
  userId: string;
  followers?:
    | {
        id: string | null;
      }[]
    | null;
  following?:
    | {
        id: string | null;
      }[]
    | null;
  blockedUsers?:
    | {
        id: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-items".
 */
export interface UserItem {
  id: number;
  /**
   * The ID of the user who owns this item
   */
  userId: string;
  /**
   * The item owned by the user
   */
  item: number | Item;
  /**
   * The number of this item owned by the user
   */
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-effects".
 */
export interface ActiveEffect {
  id: number;
  /**
   * The ID of the user who has this active effect
   */
  userId: string;
  /**
   * The type of effect that is active
   */
  effectType: 'xpBoost' | 'currencyBoost' | 'streakRestore' | 'unlockFeature';
  /**
   * The multiplier value for this effect (e.g. 1.5 for 50% boost)
   */
  multiplier: number;
  /**
   * When this effect was activated
   */
  activatedAt: string;
  /**
   * When this effect will expire
   */
  expiresAt: string;
  /**
   * Whether this effect is currently active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketplace-items".
 */
export interface MarketplaceItem {
  id: number;
  /**
   * The item being sold in the marketplace
   */
  item: number | Item;
  /**
   * The price of the item in currency
   */
  price: number;
  /**
   * Whether this item is currently available for purchase
   */
  isAvailable?: boolean | null;
  /**
   * Maximum number of times this item can be purchased (0 for unlimited)
   */
  purchaseLimit?: number | null;
  /**
   * Number of times this item has been purchased
   */
  purchaseCount?: number | null;
  /**
   * When this item becomes available for purchase
   */
  startDate?: string | null;
  /**
   * When this item will no longer be available for purchase
   */
  endDate?: string | null;
  /**
   * Optional discount information
   */
  discount?: {
    /**
     * Percentage discount (0-100)
     */
    percentage?: number | null;
    /**
     * When the discount becomes active
     */
    startDate?: string | null;
    /**
     * When the discount expires
     */
    endDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Records every instance of experience points gained by users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-logs".
 */
export interface ExperienceLog {
  id: number;
  userId: string;
  amount: number;
  timestamp: string;
  /**
   * Optional: Where the experience came from (e.g., challenge, quest).
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Represents a specific leaderboard group within a division for a given week.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-division-leaderboards".
 */
export interface WeeklyDivisionLeaderboard {
  id: number;
  /**
   * Unique identifier for the week, e.g., YYYY-W## (2024-W30).
   */
  weekIdentifier: string;
  division: number | Division;
  startDate: string;
  endDate: string;
  isProcessed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Links users to their weekly leaderboard group and tracks their performance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-leaderboard-members".
 */
export interface WeeklyLeaderboardMember {
  id: number;
  leaderboard: number | WeeklyDivisionLeaderboard;
  userId: string;
  /**
   * Total experience gained during the specific week of this leaderboard.
   */
  weeklyExperience?: number | null;
  /**
   * User's final rank within this leaderboard group for the week.
   */
  finalRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Represents technical or conceptual skills (e.g., Python, React, POO, Algorithms).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  /**
   * The name of the skill (e.g., Python, React, Object-Oriented Programming).
   */
  name: string;
  /**
   * A unique, URL-friendly identifier for the skill.
   */
  slug: string;
  /**
   * A brief description of the skill and its scope.
   */
  description?: string | null;
  /**
   * The top-level concepts that form the entry points for this skill tree.
   */
  rootConcepts?: (number | Concept)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Represents abstract concepts (e.g., Loops, Encapsulation, Stacks). Can be linked to a parent skill (e.g., Encapsulation belongs to POO).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concepts".
 */
export interface Concept {
  id: number;
  /**
   * The name of the abstract concept (e.g., Loops, Encapsulation, Stacks).
   */
  name: string;
  /**
   * A unique, URL-friendly identifier for the concept.
   */
  slug: string;
  /**
   * A brief description of the concept.
   */
  description?: string | null;
  /**
   * Distinguishes between abstract concepts (general ideas like "Loops") and concrete applications/implementations (specific tasks like "Iterate in a loop").
   */
  type: 'abstract' | 'concrete';
  /**
   * Concepts that are direct children of this concept. Used for calculating weighted average progression for abstract concepts.
   */
  subConcepts?: (number | Concept)[] | null;
  /**
   * Concepts that should generally be understood before tackling this one.
   */
  requiredConcepts?: (number | Concept)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores a user's progress on an abstract Concept.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userConceptProgressions".
 */
export interface UserConceptProgression {
  id: number;
  /**
   * The Supabase unique identifier for the user.
   */
  user: string;
  concept: number | Concept;
  /**
   * The user's current mastery level for this concept (0-100).
   */
  progressValue: number;
  /**
   * Timestamp of the last activity that contributed to this concept progression.
   */
  lastActivityAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-overall-skill-progressions".
 */
export interface UserOverallSkillProgression {
  id: number;
  user: string;
  skill: number | Skill;
  overallMasteryPercentage: number;
  lastUpdated: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-concept-outcomes".
 */
export interface ChallengeConceptOutcome {
  id: number;
  challenge: number | Challenge;
  conceptProgressions?:
    | {
        concept: number | Concept;
        completionPercentage: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conceptGroups".
 */
export interface ConceptGroup {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Courses that must be completed before starting this one.
   */
  requiredCourses?: (number | Course)[] | null;
  /**
   * Drag and drop chapters to set the learning sequence.
   */
  orderedChapters?: (number | Chapter)[] | null;
  /**
   * Title for search engines and browser tabs. Defaults to course name if empty.
   */
  metaTitle?: string | null;
  /**
   * Short description for search engines (approx. 160 chars). Defaults to start of course description if empty.
   */
  metaDescription?: string | null;
  /**
   * Comma-separated keywords (optional, less impact nowadays).
   */
  metaKeywords?: string | null;
  /**
   * Image used when sharing the course link on social media (e.g., 1200x630px).
   */
  ogImage?: (number | null) | Media;
  slug: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  /**
   * Check this box if the course requires a PRO subscription to access.
   */
  isProCourse: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Chapters that must be completed before starting this one. This might be within the same course or another, use with caution.
   */
  requiredChapters?: (number | Chapter)[] | null;
  course: number | Course;
  /**
   * The sequence of parts that make up this chapter.
   */
  parts?: (number | CoursePart)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Represents a distinct part or module within a course.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseParts".
 */
export interface CoursePart {
  id: number;
  /**
   * The title of this course part (e.g., Introduction to Variables).
   */
  name: string;
  /**
   * A unique, URL-friendly identifier for the part.
   */
  slug: string;
  /**
   * The difficulty level of this part.
   */
  difficulty: 'easy' | 'medium' | 'hard' | 'horrible';
  description: {
    /**
     * The main content or explanation for this part.
     */
    statement: string;
    /**
     * Optional hints to help the user.
     */
    hints?:
      | {
          content: string;
          isVisible?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  officialSolution?: {
    /**
     * The official solution or explanation for this part.
     */
    statement?: string | null;
  };
  /**
   * User engagement data for this part.
   */
  engagement?: {
    likes?: number | null;
    dislikes?: number | null;
  };
  /**
   * Coding challenges associated with this part.
   */
  challenges?:
    | {
        languages?:
          | {
              name: string;
              initialCode: string;
              testCases?:
                | {
                    input: string;
                    expectedOutput: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-paths".
 */
export interface LearningPath {
  id: number;
  name: string;
  slug: string;
  icon: 'binary' | 'code' | 'robotic-brain';
  description: string;
  sections: {
    name: string;
    description?: string | null;
    courses: {
      course: number | Course;
      isChoiceGroup?: boolean | null;
      choiceGroupId?: string | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user progression and engagement for specific course parts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coursePartUserProgression".
 */
export interface CoursePartUserProgression {
  id: number;
  /**
   * The ID of the user who engaged with the part.
   */
  userId: string;
  /**
   * The specific course part the user engaged with.
   */
  part: number | CoursePart;
  /**
   * The user's like/dislike status for this part.
   */
  engagementStatus: 'liked' | 'disliked' | 'none';
  /**
   * The completion status of the part for the user.
   */
  completionStatus: 'not_started' | 'in_progress' | 'completed';
  /**
   * Indicates if the user has viewed the official solution for this part.
   */
  isSolutionUnlocked: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks code submissions made by users for specific course parts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coursePartSubmissions".
 */
export interface CoursePartSubmission {
  id: number;
  /**
   * Result status of the submission for the course part code check.
   */
  submissionType: 'accepted' | 'runtimeError' | 'wrongAnswer' | 'timeLimitExceeded';
  /**
   * The course part this submission belongs to.
   */
  part: number | CoursePart;
  /**
   * The ID of the user who made this submission.
   */
  authorId: string;
  /**
   * Number of test cases passed.
   */
  testsPassed: number;
  /**
   * Total number of test cases for the part.
   */
  testsTotal: number;
  code: {
    /**
     * Programming language used.
     */
    language: string;
    /**
     * Source code submitted.
     */
    content: string;
  };
  /**
   * Error message for runtime error submissions.
   */
  error?: string | null;
  /**
   * Last expected outputs (for runtime/timeout errors).
   */
  lastExpectedOutput?:
    | {
        output?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Input that caused the wrong answer.
   */
  input?: string | null;
  /**
   * Actual output produced for wrong answer.
   */
  output?: string | null;
  /**
   * Expected output for wrong answer.
   */
  expectedOutput?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks user progression status for entire course chapters.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChapterProgress".
 */
export interface UserChapterProgress {
  id: number;
  /**
   * The ID of the user.
   */
  userId: string;
  /**
   * The specific chapter this progression refers to.
   */
  chapter: number | Chapter;
  /**
   * The overall completion status of the chapter for the user.
   */
  completionStatus: 'not_started' | 'in_progress' | 'completed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Feedback submitted by users for specific course parts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coursePartFeedback".
 */
export interface CoursePartFeedback {
  id: number;
  /**
   * The specific course part this feedback relates to.
   */
  part: number | CoursePart;
  /**
   * The category of the feedback provided.
   */
  feedbackType: 'typo' | 'error' | 'unclear' | 'suggestion' | 'other';
  /**
   * The detailed feedback submitted by the user.
   */
  details: string;
  /**
   * The current status of this feedback item.
   */
  status: 'new' | 'acknowledged' | 'resolved' | 'rejected';
  /**
   * The UUID of the user who submitted the feedback.
   */
  userId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-onboarding".
 */
export interface UserOnboarding {
  id: number;
  userId: string;
  skipped: boolean;
  codingLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  timeCoding?: ('less-than-6-months' | 'less-than-1-year' | '1-2-years' | '3-5-years' | '5-plus-years') | null;
  selectedLanguages?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  selectedConcepts?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  selectedGoals?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  selectedTechnologiesToLearn?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-articles".
 */
export interface BlogArticle {
  id: number;
  title: string;
  /**
   * URL-friendly identifier for this blog article. Will be used in the URL.
   */
  slug: string;
  /**
   * The main content of the blog article, written in Markdown.
   */
  content: string;
  /**
   * A brief description or summary of the blog article.
   */
  description: string;
  /**
   * The category this blog article belongs to.
   */
  category: 'engineering' | 'changelog';
  author: number | User;
  /**
   * The date and time when the article was published.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeEngagement".
 */
export interface UserChallengeEngagement {
  id: number;
  /**
   * ID of the user
   */
  userId: string;
  /**
   * Related challenge
   */
  challenge: number | Challenge;
  /**
   * Whether the user has liked this challenge
   */
  hasLiked?: boolean | null;
  /**
   * Whether the user has disliked this challenge
   */
  hasDisliked?: boolean | null;
  /**
   * User rating for this challenge (1-5)
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeCompletionStatus".
 */
export interface UserChallengeCompletionStatus {
  id: number;
  /**
   * ID of the user
   */
  userId: string;
  /**
   * Related challenge
   */
  challenge: number | Challenge;
  /**
   * Current completion status of the challenge
   */
  completionStatus: 'not_started' | 'in_progress' | 'completed';
  /**
   * Whether the solution has been unlocked by the user
   */
  isSolutionUnlocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeCode".
 */
export interface UserChallengeCode {
  id: number;
  /**
   * ID of the user
   */
  userId: string;
  /**
   * Related challenge
   */
  challenge: number | Challenge;
  /**
   * Code submissions for this challenge
   */
  code?:
    | {
        /**
         * Programming language of the code
         */
        language: string;
        /**
         * The actual code content
         */
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-login-entries".
 */
export interface DailyLoginEntry {
  id: number;
  /**
   * The Supabase user ID
   */
  userId: string;
  /**
   * The date when the user logged in
   */
  date: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-streaks".
 */
export interface ChallengeStreak {
  id: number;
  /**
   * The Supabase user ID
   */
  userId: string;
  /**
   * The date of the challenge completion streak.
   */
  date: string;
  /**
   * The number of challenges completed on this date.
   */
  challengesCompleted: number;
  /**
   * The status of the streak for this day.
   */
  status: 'active' | 'frozen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-ai-chats".
 */
export interface ChallengeAiChat {
  id: number;
  userId: string;
  challenge: number | Challenge;
  chatHistory?: (number | null) | ChatHistory;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-histories".
 */
export interface ChatHistory {
  id: number;
  chat: number | ChallengeAiChat;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-ai-usage".
 */
export interface UserAiUsage {
  id: number;
  userId: string;
  date: string;
  messagesUsed: number;
  dailyLimit: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-ai-credits".
 */
export interface UserAiCredit {
  id: number;
  userId: string;
  balance: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-rating".
 */
export interface ChallengeRating {
  id: number;
  /**
   * The challenge being rated
   */
  challenge: number | Challenge;
  /**
   * The user who gave the rating
   */
  userId: string;
  /**
   * Rating value (1-5)
   */
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges-ratings".
 */
export interface ChallengesRating {
  id: number;
  /**
   * The challenge this rating aggregate is for
   */
  challenge: number | Challenge;
  /**
   * Sum of all rating points
   */
  total?: number | null;
  /**
   * Number of ratings received
   */
  count?: number | null;
  /**
   * Average rating (0-5)
   */
  average?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-engagement".
 */
export interface ChallengeEngagement {
  id: number;
  /**
   * The challenge being engaged with
   */
  challenge: number | Challenge;
  /**
   * The user who liked/disliked
   */
  userId: string;
  /**
   * Type of engagement (like or dislike)
   */
  type: 'like' | 'dislike';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges-engagement".
 */
export interface ChallengesEngagement {
  id: number;
  /**
   * The challenge for which engagement stats are tracked
   */
  challenge: number | Challenge;
  /**
   * Number of likes
   */
  likes?: number | null;
  /**
   * Number of dislikes
   */
  dislikes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercices".
 */
export interface Exercice {
  id: number;
  /**
   * The title of the exercice
   */
  title: string;
  /**
   * The difficulty level of the exercice
   */
  difficulty: 'very_easy' | 'easy' | 'medium' | 'hard' | 'horrible';
  /**
   * Helpful hints for solving the exercice
   */
  hints?:
    | {
        content: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Supported languages for this exercice
   */
  languages: {
    language: 'python' | 'javascript' | 'typescript';
    /**
     * Initial code provided to users (optional)
     */
    initialCode?: string | null;
    /**
     * Test cases for validating solutions in this language
     */
    testCases: {
      /**
       * Input data for the test case
       */
      input: string;
      /**
       * Expected output for this test case
       */
      expectedOutput: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tutorials';
        value: number | Tutorial;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'support-settings';
        value: number | SupportSetting;
      } | null)
    | ({
        relationTo: 'user-informations';
        value: number | UserInformation;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'user-gamification';
        value: number | UserGamification;
      } | null)
    | ({
        relationTo: 'user-inventory';
        value: number | UserInventory;
      } | null)
    | ({
        relationTo: 'user-currency';
        value: number | UserCurrency;
      } | null)
    | ({
        relationTo: 'quests';
        value: number | Quest;
      } | null)
    | ({
        relationTo: 'user-quests';
        value: number | UserQuest;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'user-achievement-progress';
        value: number | UserAchievementProgress;
      } | null)
    | ({
        relationTo: 'challenges';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'userChallengeProgression';
        value: number | UserChallengeProgression;
      } | null)
    | ({
        relationTo: 'challenge-submissions';
        value: number | ChallengeSubmission;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'challenge-categories';
        value: number | ChallengeCategory;
      } | null)
    | ({
        relationTo: 'user-following-informations';
        value: number | UserFollowingInformation;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'user-items';
        value: number | UserItem;
      } | null)
    | ({
        relationTo: 'active-effects';
        value: number | ActiveEffect;
      } | null)
    | ({
        relationTo: 'marketplace-items';
        value: number | MarketplaceItem;
      } | null)
    | ({
        relationTo: 'divisions';
        value: number | Division;
      } | null)
    | ({
        relationTo: 'experience-logs';
        value: number | ExperienceLog;
      } | null)
    | ({
        relationTo: 'weekly-division-leaderboards';
        value: number | WeeklyDivisionLeaderboard;
      } | null)
    | ({
        relationTo: 'weekly-leaderboard-members';
        value: number | WeeklyLeaderboardMember;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'concepts';
        value: number | Concept;
      } | null)
    | ({
        relationTo: 'userConceptProgressions';
        value: number | UserConceptProgression;
      } | null)
    | ({
        relationTo: 'user-overall-skill-progressions';
        value: number | UserOverallSkillProgression;
      } | null)
    | ({
        relationTo: 'challenge-concept-outcomes';
        value: number | ChallengeConceptOutcome;
      } | null)
    | ({
        relationTo: 'conceptGroups';
        value: number | ConceptGroup;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'learning-paths';
        value: number | LearningPath;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'courseParts';
        value: number | CoursePart;
      } | null)
    | ({
        relationTo: 'coursePartUserProgression';
        value: number | CoursePartUserProgression;
      } | null)
    | ({
        relationTo: 'coursePartSubmissions';
        value: number | CoursePartSubmission;
      } | null)
    | ({
        relationTo: 'userChapterProgress';
        value: number | UserChapterProgress;
      } | null)
    | ({
        relationTo: 'coursePartFeedback';
        value: number | CoursePartFeedback;
      } | null)
    | ({
        relationTo: 'user-onboarding';
        value: number | UserOnboarding;
      } | null)
    | ({
        relationTo: 'blog-articles';
        value: number | BlogArticle;
      } | null)
    | ({
        relationTo: 'userChallengeEngagement';
        value: number | UserChallengeEngagement;
      } | null)
    | ({
        relationTo: 'userChallengeCompletionStatus';
        value: number | UserChallengeCompletionStatus;
      } | null)
    | ({
        relationTo: 'userChallengeCode';
        value: number | UserChallengeCode;
      } | null)
    | ({
        relationTo: 'daily-login-entries';
        value: number | DailyLoginEntry;
      } | null)
    | ({
        relationTo: 'challenge-streaks';
        value: number | ChallengeStreak;
      } | null)
    | ({
        relationTo: 'challenge-ai-chats';
        value: number | ChallengeAiChat;
      } | null)
    | ({
        relationTo: 'user-ai-usage';
        value: number | UserAiUsage;
      } | null)
    | ({
        relationTo: 'user-ai-credits';
        value: number | UserAiCredit;
      } | null)
    | ({
        relationTo: 'chat-histories';
        value: number | ChatHistory;
      } | null)
    | ({
        relationTo: 'challenge-rating';
        value: number | ChallengeRating;
      } | null)
    | ({
        relationTo: 'challenges-ratings';
        value: number | ChallengesRating;
      } | null)
    | ({
        relationTo: 'challenge-engagement';
        value: number | ChallengeEngagement;
      } | null)
    | ({
        relationTo: 'challenges-engagement';
        value: number | ChallengesEngagement;
      } | null)
    | ({
        relationTo: 'exercices';
        value: number | Exercice;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  articleStatus?: T;
  difficultyLevel?: T;
  author?: T;
  tags?: T;
  analytics?:
    | T
    | {
        views?: T;
        uniqueViews?: T;
        recommendationClicks?: T;
        averageTimeSpent?: T;
        bounceRate?: T;
        ratingCount?: T;
        ratingSum?: T;
      };
  translations?:
    | T
    | {
        language?: T;
        title?: T;
        subtitle?: T;
        content?: T;
        translator?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?:
                | T
                | {
                    keyword?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  relatedArticles?: T;
  prerequisites?: T;
  nextSteps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials_select".
 */
export interface TutorialsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  tutorialStatus?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        articles?: T;
        id?: T;
      };
  exampleSections?:
    | T
    | {
        title?: T;
        articles?: T;
        id?: T;
      };
  referenceSections?:
    | T
    | {
        title?: T;
        description?: T;
        articles?: T;
        id?: T;
      };
  translations?:
    | T
    | {
        language?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  usageCount?: T;
  creatorId?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  message?: T;
  articleSlug?: T;
  tutorialSlug?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-settings_select".
 */
export interface SupportSettingsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  maintenanceMessage?: T;
  offlineMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-informations_select".
 */
export interface UserInformationsSelect<T extends boolean = true> {
  userId?: T;
  name?: T;
  avatar?: T;
  initials?: T;
  role?: T;
  permissions?: T;
  preferences?:
    | T
    | {
        notifications?:
          | T
          | {
              friends?: T;
            };
        emails?:
          | T
          | {
              marketing?: T;
              affiliates?: T;
            };
        theme?: T;
      };
  customerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  code?: T;
  category?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-gamification_select".
 */
export interface UserGamificationSelect<T extends boolean = true> {
  userId?: T;
  currentLevel?: T;
  currentExperience?: T;
  totalExperience?: T;
  lastLevelUpDate?: T;
  division?: T;
  dailyQuestReplacementsUsed?: T;
  lastQuestReplacementDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-inventory_select".
 */
export interface UserInventorySelect<T extends boolean = true> {
  userId?: T;
  items?:
    | T
    | {
        itemEntries?:
          | T
          | {
              itemType?: T;
              itemVariant?: T;
              quantity?: T;
              id?: T;
            };
      };
  itemCount?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-currency_select".
 */
export interface UserCurrencySelect<T extends boolean = true> {
  userId?: T;
  quantity?: T;
  transactionHistory?:
    | T
    | {
        timestamp?: T;
        type?: T;
        amount?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests_select".
 */
export interface QuestsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  difficulty?: T;
  value?: T;
  experience?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-quests_select".
 */
export interface UserQuestsSelect<T extends boolean = true> {
  userId?: T;
  quest?: T;
  currentProgression?: T;
  isCompleted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  icon?: T;
  maxTier?: T;
  tiers?:
    | T
    | {
        name?: T;
        description?: T;
        threshold?: T;
        rewardCoins?: T;
        rewardXp?: T;
        rewardItem?: T;
        id?: T;
      };
  nextAchievement?: T;
  isActive?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-achievement-progress_select".
 */
export interface UserAchievementProgressSelect<T extends boolean = true> {
  userId?: T;
  achievement?: T;
  currentProgress?: T;
  currentTierIndex?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  difficulty?: T;
  baseExperience?: T;
  description?:
    | T
    | {
        statement?: T;
        hints?:
          | T
          | {
              content?: T;
              id?: T;
            };
        similarChallenges?:
          | T
          | {
              challenge?: T;
              id?: T;
            };
      };
  officialSolution?:
    | T
    | {
        statement?: T;
      };
  codeVersions?:
    | T
    | {
        language?: T;
        initialCode?: T;
        testCases?:
          | T
          | {
              input?: T;
              expectedOutput?: T;
              id?: T;
            };
        id?: T;
      };
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeProgression_select".
 */
export interface UserChallengeProgressionSelect<T extends boolean = true> {
  userId?: T;
  challenge?: T;
  hasLiked?: T;
  hasDisliked?: T;
  rating?: T;
  completionStatus?: T;
  isSolutionUnlocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-submissions_select".
 */
export interface ChallengeSubmissionsSelect<T extends boolean = true> {
  submissionType?: T;
  challenge?: T;
  authorId?: T;
  testsPassed?: T;
  testsTotal?: T;
  code?:
    | T
    | {
        language?: T;
        content?: T;
      };
  error?: T;
  lastExpectedOutput?:
    | T
    | {
        output?: T;
        id?: T;
      };
  input?: T;
  output?: T;
  expectedOutput?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  userId?: T;
  content?: T;
  importance?: T;
  type?: T;
  isRead?: T;
  actionUrl?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-categories_select".
 */
export interface ChallengeCategoriesSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  description?: T;
  slug?: T;
  isLocked?: T;
  parts?:
    | T
    | {
        name?: T;
        description?: T;
        challenges?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-following-informations_select".
 */
export interface UserFollowingInformationsSelect<T extends boolean = true> {
  userId?: T;
  followers?:
    | T
    | {
        id?: T;
      };
  following?:
    | T
    | {
        id?: T;
      };
  blockedUsers?:
    | T
    | {
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  activationMode?: T;
  multiplier?: T;
  duration?: T;
  appliesPassively?: T;
  icon?: T;
  rarity?: T;
  chestRewards?:
    | T
    | {
        minCoins?: T;
        maxCoins?: T;
        minXp?: T;
        maxXp?: T;
        commonItemsCount?: T;
        rareItemsCount?: T;
        epicItemsCount?: T;
        legendaryItemsCount?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-items_select".
 */
export interface UserItemsSelect<T extends boolean = true> {
  userId?: T;
  item?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-effects_select".
 */
export interface ActiveEffectsSelect<T extends boolean = true> {
  userId?: T;
  effectType?: T;
  multiplier?: T;
  activatedAt?: T;
  expiresAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketplace-items_select".
 */
export interface MarketplaceItemsSelect<T extends boolean = true> {
  item?: T;
  price?: T;
  isAvailable?: T;
  purchaseLimit?: T;
  purchaseCount?: T;
  startDate?: T;
  endDate?: T;
  discount?:
    | T
    | {
        percentage?: T;
        startDate?: T;
        endDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions_select".
 */
export interface DivisionsSelect<T extends boolean = true> {
  name?: T;
  levelRequirement?: T;
  promotionThreshold?: T;
  demotionThreshold?: T;
  rankOrder?: T;
  rewards?:
    | T
    | {
        rankStart?: T;
        rankEnd?: T;
        coinAmount?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-logs_select".
 */
export interface ExperienceLogsSelect<T extends boolean = true> {
  userId?: T;
  amount?: T;
  timestamp?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-division-leaderboards_select".
 */
export interface WeeklyDivisionLeaderboardsSelect<T extends boolean = true> {
  weekIdentifier?: T;
  division?: T;
  startDate?: T;
  endDate?: T;
  isProcessed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-leaderboard-members_select".
 */
export interface WeeklyLeaderboardMembersSelect<T extends boolean = true> {
  leaderboard?: T;
  userId?: T;
  weeklyExperience?: T;
  finalRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  rootConcepts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concepts_select".
 */
export interface ConceptsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  subConcepts?: T;
  requiredConcepts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userConceptProgressions_select".
 */
export interface UserConceptProgressionsSelect<T extends boolean = true> {
  user?: T;
  concept?: T;
  progressValue?: T;
  lastActivityAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-overall-skill-progressions_select".
 */
export interface UserOverallSkillProgressionsSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  overallMasteryPercentage?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-concept-outcomes_select".
 */
export interface ChallengeConceptOutcomesSelect<T extends boolean = true> {
  challenge?: T;
  conceptProgressions?:
    | T
    | {
        concept?: T;
        completionPercentage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conceptGroups_select".
 */
export interface ConceptGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  requiredCourses?: T;
  orderedChapters?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  ogImage?: T;
  slug?: T;
  difficulty?: T;
  isProCourse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-paths_select".
 */
export interface LearningPathsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  description?: T;
  sections?:
    | T
    | {
        name?: T;
        description?: T;
        courses?:
          | T
          | {
              course?: T;
              isChoiceGroup?: T;
              choiceGroupId?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  requiredChapters?: T;
  course?: T;
  parts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseParts_select".
 */
export interface CoursePartsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  difficulty?: T;
  description?:
    | T
    | {
        statement?: T;
        hints?:
          | T
          | {
              content?: T;
              isVisible?: T;
              id?: T;
            };
      };
  officialSolution?:
    | T
    | {
        statement?: T;
      };
  engagement?:
    | T
    | {
        likes?: T;
        dislikes?: T;
      };
  challenges?:
    | T
    | {
        languages?:
          | T
          | {
              name?: T;
              initialCode?: T;
              testCases?:
                | T
                | {
                    input?: T;
                    expectedOutput?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coursePartUserProgression_select".
 */
export interface CoursePartUserProgressionSelect<T extends boolean = true> {
  userId?: T;
  part?: T;
  engagementStatus?: T;
  completionStatus?: T;
  isSolutionUnlocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coursePartSubmissions_select".
 */
export interface CoursePartSubmissionsSelect<T extends boolean = true> {
  submissionType?: T;
  part?: T;
  authorId?: T;
  testsPassed?: T;
  testsTotal?: T;
  code?:
    | T
    | {
        language?: T;
        content?: T;
      };
  error?: T;
  lastExpectedOutput?:
    | T
    | {
        output?: T;
        id?: T;
      };
  input?: T;
  output?: T;
  expectedOutput?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChapterProgress_select".
 */
export interface UserChapterProgressSelect<T extends boolean = true> {
  userId?: T;
  chapter?: T;
  completionStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coursePartFeedback_select".
 */
export interface CoursePartFeedbackSelect<T extends boolean = true> {
  part?: T;
  feedbackType?: T;
  details?: T;
  status?: T;
  userId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-onboarding_select".
 */
export interface UserOnboardingSelect<T extends boolean = true> {
  userId?: T;
  skipped?: T;
  codingLevel?: T;
  timeCoding?: T;
  selectedLanguages?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  selectedConcepts?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  selectedGoals?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  selectedTechnologiesToLearn?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-articles_select".
 */
export interface BlogArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  description?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeEngagement_select".
 */
export interface UserChallengeEngagementSelect<T extends boolean = true> {
  userId?: T;
  challenge?: T;
  hasLiked?: T;
  hasDisliked?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeCompletionStatus_select".
 */
export interface UserChallengeCompletionStatusSelect<T extends boolean = true> {
  userId?: T;
  challenge?: T;
  completionStatus?: T;
  isSolutionUnlocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeCode_select".
 */
export interface UserChallengeCodeSelect<T extends boolean = true> {
  userId?: T;
  challenge?: T;
  code?:
    | T
    | {
        language?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-login-entries_select".
 */
export interface DailyLoginEntriesSelect<T extends boolean = true> {
  userId?: T;
  date?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-streaks_select".
 */
export interface ChallengeStreaksSelect<T extends boolean = true> {
  userId?: T;
  date?: T;
  challengesCompleted?: T;
  status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-ai-chats_select".
 */
export interface ChallengeAiChatsSelect<T extends boolean = true> {
  userId?: T;
  challenge?: T;
  chatHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-ai-usage_select".
 */
export interface UserAiUsageSelect<T extends boolean = true> {
  userId?: T;
  date?: T;
  messagesUsed?: T;
  dailyLimit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-ai-credits_select".
 */
export interface UserAiCreditsSelect<T extends boolean = true> {
  userId?: T;
  balance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-histories_select".
 */
export interface ChatHistoriesSelect<T extends boolean = true> {
  chat?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-rating_select".
 */
export interface ChallengeRatingSelect<T extends boolean = true> {
  challenge?: T;
  userId?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges-ratings_select".
 */
export interface ChallengesRatingsSelect<T extends boolean = true> {
  challenge?: T;
  total?: T;
  count?: T;
  average?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-engagement_select".
 */
export interface ChallengeEngagementSelect<T extends boolean = true> {
  challenge?: T;
  userId?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges-engagement_select".
 */
export interface ChallengesEngagementSelect<T extends boolean = true> {
  challenge?: T;
  likes?: T;
  dislikes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercices_select".
 */
export interface ExercicesSelect<T extends boolean = true> {
  title?: T;
  difficulty?: T;
  hints?:
    | T
    | {
        content?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        initialCode?: T;
        testCases?:
          | T
          | {
              input?: T;
              expectedOutput?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}