/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    tutorials: Tutorial;
    tags: Tag;
    feedbacks: Feedback;
    'support-settings': SupportSetting;
    'user-informations': UserInformation;
    permissions: Permission;
    'user-gamification': UserGamification;
    'user-inventory': UserInventory;
    'user-currency': UserCurrency;
    quests: Quest;
    'user-quests': UserQuest;
    achievements: Achievement;
    'user-achievements': UserAchievement;
    challenges: Challenge;
    userChallengeProgression: UserChallengeProgression;
    comments: Comment;
    'user-solutions': UserSolution;
    'challenge-submissions': ChallengeSubmission;
    notifications: Notification;
    skills: Skill;
    'base-concepts': BaseConcept;
    'skill-concepts': SkillConcept;
    'challenge-categories': ChallengeCategory;
    'user-following-informations': UserFollowingInformation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tutorials: TutorialsSelect<false> | TutorialsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    'support-settings': SupportSettingsSelect<false> | SupportSettingsSelect<true>;
    'user-informations': UserInformationsSelect<false> | UserInformationsSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    'user-gamification': UserGamificationSelect<false> | UserGamificationSelect<true>;
    'user-inventory': UserInventorySelect<false> | UserInventorySelect<true>;
    'user-currency': UserCurrencySelect<false> | UserCurrencySelect<true>;
    quests: QuestsSelect<false> | QuestsSelect<true>;
    'user-quests': UserQuestsSelect<false> | UserQuestsSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    'user-achievements': UserAchievementsSelect<false> | UserAchievementsSelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    userChallengeProgression: UserChallengeProgressionSelect<false> | UserChallengeProgressionSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'user-solutions': UserSolutionsSelect<false> | UserSolutionsSelect<true>;
    'challenge-submissions': ChallengeSubmissionsSelect<false> | ChallengeSubmissionsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'base-concepts': BaseConceptsSelect<false> | BaseConceptsSelect<true>;
    'skill-concepts': SkillConceptsSelect<false> | SkillConceptsSelect<true>;
    'challenge-categories': ChallengeCategoriesSelect<false> | ChallengeCategoriesSelect<true>;
    'user-following-informations': UserFollowingInformationsSelect<false> | UserFollowingInformationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-friendly identifier for this article. Will be used in the URL.
   */
  slug: string;
  subtitle?: string | null;
  content: string;
  /**
   * Information for search engine optimization (SEO) of the article in the main language (English)
   */
  seo?: {
    /**
     * Optimized title for search engines (if different from the main title)
     */
    title?: string | null;
    /**
     * Short description for search results (150-160 characters recommended)
     */
    description?: string | null;
    /**
     * Relevant keywords for SEO
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Article visibility (independent from the draft/publish system)
   */
  articleStatus: 'active' | 'archived';
  /**
   * Difficulty level of the article
   */
  difficultyLevel: 'beginner' | 'intermediate' | 'advanced';
  author: number | User;
  /**
   * Concepts related to this article (e.g., "python", "object-oriented")
   */
  tags?: (number | Tag)[] | null;
  /**
   * Engagement metrics for this article (normally updated automatically)
   */
  analytics?: {
    /**
     * Total number of article views
     */
    views?: number | null;
    /**
     * Number of distinct visitors who viewed the article
     */
    uniqueViews?: number | null;
    /**
     * Number of times the article was viewed from a recommendation
     */
    recommendationClicks?: number | null;
    /**
     * Average time spent on the article in seconds
     */
    averageTimeSpent?: number | null;
    /**
     * Percentage of users who leave after viewing only this article
     */
    bounceRate?: number | null;
    /**
     * Total number of ratings received for this article
     */
    ratingCount?: number | null;
    /**
     * Sum of all ratings (scale of 1 to 5) - allows calculating the average
     */
    ratingSum?: number | null;
  };
  /**
   * Add translations for this article (the default language is English)
   */
  translations?:
    | {
        language: 'fr' | 'es';
        title: string;
        subtitle?: string | null;
        content: string;
        translator?: (number | null) | User;
        /**
         * Information for search engine optimization (SEO) of this translation
         */
        seo?: {
          /**
           * Optimized title for search engines (if different from the translated title)
           */
          title?: string | null;
          /**
           * Short description for search results (150-160 characters recommended)
           */
          description?: string | null;
          /**
           * Relevant keywords for SEO in this language
           */
          keywords?:
            | {
                keyword?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Select articles that are related to this article
   */
  relatedArticles?: (number | Article)[] | null;
  /**
   * Articles that should be read before this one
   */
  prerequisites?: (number | Article)[] | null;
  /**
   * Recommended articles to read after this one
   */
  nextSteps?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  status: 'test' | 'public';
  usageCount: number;
  creatorId: string;
  lastUsedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials".
 */
export interface Tutorial {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Tutorial visibility (independent from the draft/publish system)
   */
  tutorialStatus: 'active' | 'archived';
  /**
   * Sections of the tutorial, each containing a list of articles
   */
  sections: {
    title: string;
    description?: string | null;
    /**
     * Articles included in this section, in display order
     */
    articles: (number | Article)[];
    id?: string | null;
  }[];
  /**
   * Example sections for this tutorial, each grouping similar articles
   */
  exampleSections?:
    | {
        title: string;
        /**
         * Example articles included in this section
         */
        articles: (number | Article)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Reference article sections for this tutorial, organized by theme or category
   */
  referenceSections?:
    | {
        title: string;
        description?: string | null;
        /**
         * Reference articles included in this section
         */
        articles: (number | Article)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Add translations for the tutorial title (the default language is English)
   */
  translations?:
    | {
        language: 'fr' | 'es';
        title: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  message: string;
  /**
   * The slug of the article where the feedback was submitted
   */
  articleSlug?: string | null;
  /**
   * The slug of the tutorial where the feedback was submitted
   */
  tutorialSlug?: string | null;
  /**
   * IP address of the user who submitted the feedback (for rate limiting)
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-settings".
 */
export interface SupportSetting {
  id: number;
  /**
   * Name of the settings (should be "Support Settings")
   */
  name: string;
  /**
   * Current status of the support system
   */
  status: 'online' | 'maintenance' | 'offline';
  /**
   * Message to display when support is in maintenance mode
   */
  maintenanceMessage?: string | null;
  /**
   * Message to display when support is offline
   */
  offlineMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-informations".
 */
export interface UserInformation {
  id: number;
  userId: string;
  name?: string | null;
  avatar?: string | null;
  initials?: string | null;
  role: 'basic' | 'lite' | 'pro' | 'max';
  /**
   * Select permissions for this user
   */
  permissions?: (number | Permission)[] | null;
  preferences?: {
    notifications?: {
      friends?: boolean | null;
    };
    emails?: {
      marketing?: boolean | null;
      affiliates?: boolean | null;
    };
    theme?: ('light' | 'dark' | 'system') | null;
  };
  customerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Unique code used to identify this permission in the system
   */
  code: string;
  category?: ('content' | 'users' | 'system' | 'other') | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-gamification".
 */
export interface UserGamification {
  id: number;
  /**
   * The ID of the user this gamification data belongs to
   */
  userId: string;
  /**
   * The current level of the user
   */
  currentLevel: number;
  /**
   * The current experience points towards the next level
   */
  currentExperience: number;
  /**
   * The total experience points earned by the user
   */
  totalExperience: number;
  /**
   * The date when the user last leveled up
   */
  lastLevelUpDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-inventory".
 */
export interface UserInventory {
  id: number;
  /**
   * The ID of the user this inventory belongs to
   */
  userId: string;
  /**
   * Items in the user's inventory
   */
  items?: {
    /**
     * List of items in the inventory
     */
    itemEntries?:
      | {
          /**
           * The type of the item
           */
          itemType: 'experience_boost' | 'streak_saver' | 'streak_recovery' | 'solution_viewer' | 'chest';
          /**
           * The specific variant of the item (e.g., "basic", "premium", "legendary")
           */
          itemVariant: 'basic' | 'premium' | 'legendary';
          /**
           * The quantity of this item
           */
          quantity: number;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Total number of items in the inventory
   */
  itemCount?: number | null;
  /**
   * When this inventory was last updated
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-currency".
 */
export interface UserCurrency {
  id: number;
  /**
   * The ID of the user this currency belongs to
   */
  userId: string;
  /**
   * Standard currency earned through regular activities
   */
  coins: number;
  /**
   * History of currency transactions
   */
  transactionHistory?:
    | {
        /**
         * When the transaction occurred
         */
        timestamp: string;
        /**
         * The type of transaction
         */
        type: 'earn' | 'spend' | 'admin_adjustment';
        /**
         * The amount of coins (positive for earning, negative for spending)
         */
        amount: number;
        /**
         * The source or reason for the transaction (e.g., "daily_challenge", "level_up", "achievement")
         */
        source?: string | null;
        /**
         * Additional details about the transaction
         */
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When this currency record was last updated
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests".
 */
export interface Quest {
  id: number;
  title: string;
  type: 'experienceGained' | 'challengesCompleted' | 'increasedLevel';
  difficulty: 'easy' | 'medium' | 'hard';
  value: number;
  experience: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-quests".
 */
export interface UserQuest {
  id: number;
  userId: string;
  quest: number | Quest;
  currentProgression: number;
  isCompleted: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  /**
   * The title of the achievement
   */
  title: string;
  /**
   * The type of achievement that determines how progress is calculated
   */
  type:
    | 'level'
    | 'exercises_completed'
    | 'streak'
    | 'tutorials_completed'
    | 'quests_completed'
    | 'items_used'
    | 'coins_earned';
  /**
   * The icon identifier for this achievement
   */
  icon?: string | null;
  /**
   * The maximum number of tiers for this achievement (typically 4 for Bronze, Silver, Gold, Diamond)
   */
  maxTier: number;
  /**
   * The different tiers of the achievement
   */
  tiers: {
    /**
     * The name of the tier (Bronze, Silver, Gold, etc.)
     */
    name: 'bronze' | 'silver' | 'gold' | 'diamond' | 'platinum';
    /**
     * The description specific to this achievement tier
     */
    description: string;
    /**
     * The value to reach to obtain this achievement tier
     */
    threshold: number;
    /**
     * The number of coins given as a reward for this tier
     */
    rewardCoins: number;
    /**
     * The number of experience points given as a reward for this tier
     */
    rewardXp: number;
    id?: string | null;
  }[];
  /**
   * Indicates if this achievement is currently active in the system
   */
  isActive?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-achievements".
 */
export interface UserAchievement {
  id: number;
  /**
   * The ID of the user this progress belongs to
   */
  userId: string;
  /**
   * List of the user's achievement progresses
   */
  achievements?:
    | {
        /**
         * The achievement this progress is linked to
         */
        achievementId: number | Achievement;
        /**
         * The current progress value for this achievement
         */
        currentValue: number;
        /**
         * The current tier reached for this achievement
         */
        currentTier?: ('none' | 'bronze' | 'silver' | 'gold' | 'diamond' | 'platinum') | null;
        /**
         * The tiers unlocked for this achievement
         */
        unlockedTiers?:
          | {
              /**
               * The unlocked tier
               */
              tier: 'bronze' | 'silver' | 'gold' | 'diamond' | 'platinum';
              /**
               * The date when this tier was unlocked
               */
              unlockedAt: string;
              /**
               * Indicates if the reward for this tier has been claimed
               */
              rewardClaimed?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * The date of the last update for this progress
         */
        lastUpdated?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The total number of achievements unlocked by the user
   */
  totalAchievements?: number | null;
  /**
   * The date of the last update for this collection
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: number;
  /**
   * The title of the challenge
   */
  title: string;
  /**
   * URL-friendly identifier for this challenge. Will be used in the URL.
   */
  slug: string;
  /**
   * The difficulty level of the challenge
   */
  difficulty: 'easy' | 'medium' | 'hard' | 'horrible';
  /**
   * Experience points awarded for completing this challenge (calculated automatically)
   */
  baseExperience?: number | null;
  /**
   * User ratings for this challenge
   */
  ratings?: {
    /**
     * Sum of all rating points
     */
    total?: number | null;
    /**
     * Number of ratings received
     */
    count?: number | null;
    /**
     * Average rating (0-5)
     */
    average?: number | null;
  };
  /**
   * Programming concepts covered by this challenge
   */
  concepts?:
    | {
        concept: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Challenge engagement metrics
   */
  engagement?: {
    /**
     * Number of likes received
     */
    likes?: number | null;
    /**
     * Number of dislikes received
     */
    dislikes?: number | null;
  };
  /**
   * Challenge description and problem statement
   */
  description: {
    /**
     * Problem statement and challenge description
     */
    statement: string;
    /**
     * Statistics about challenge submissions
     */
    submissionStats?: {
      /**
       * Number of accepted solutions
       */
      acceptedSolutions?: number | null;
      /**
       * Number of failed solutions
       */
      failedSolutions?: number | null;
      /**
       * Total number of submissions
       */
      totalSubmissions?: number | null;
      /**
       * Percentage of accepted submissions (0-100)
       */
      acceptanceRate?: number | null;
    };
    /**
     * Helpful hints for solving the challenge
     */
    hints?:
      | {
          content: string;
          id?: string | null;
        }[]
      | null;
    /**
     * List of related challenges
     */
    similarChallenges?:
      | {
          /**
           * Select a related challenge
           */
          challenge: number | Challenge;
          id?: string | null;
        }[]
      | null;
    /**
     * Comments on this challenge description
     */
    comments?: (number | Comment)[] | null;
  };
  /**
   * The official solution for this challenge
   */
  officialSolution: {
    /**
     * The content of the official solution
     */
    statement: string;
    /**
     * Comments on this official solution
     */
    comments?: (number | Comment)[] | null;
  };
  /**
   * Solutions submitted by users for this challenge
   */
  userSolutions?: (number | UserSolution)[] | null;
  /**
   * Submissions made by users for this challenge
   */
  submissions?:
    | {
        /**
         * Type of submission result
         */
        submissionType: 'accepted' | 'runtimeError' | 'wrongAnswer' | 'timeLimitExceeded';
        /**
         * ID of the user who made this submission
         */
        authorId: string;
        /**
         * Number of test cases passed
         */
        testsPassed: number;
        /**
         * Total number of test cases
         */
        testsTotal: number;
        /**
         * When this submission was made
         */
        createdAt?: string | null;
        /**
         * Error message (for Runtime Error submissions)
         */
        error?: string | null;
        /**
         * Test case input (for Wrong Answer submissions)
         */
        input?: string | null;
        /**
         * User's output (for Wrong Answer submissions)
         */
        output?: string | null;
        /**
         * Expected output (for Wrong Answer submissions)
         */
        expectedOutput?: string | null;
        /**
         * Last expected output parameters (for Runtime Error and Time Limit Exceeded submissions)
         */
        lastExpectedOutput?:
          | {
              param: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * The submitted code
         */
        code: {
          /**
           * Programming language of the submission
           */
          language: string;
          /**
           * The code content
           */
          content: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Code related information for this challenge (Legacy field - Use codeVersions instead)
   */
  code: {
    /**
     * Default programming language for the challenge
     */
    language: string;
    /**
     * Initial code provided to users
     */
    initialCode: string;
    /**
     * Test cases for validating solutions
     */
    testCases?:
      | {
          /**
           * Input data for the test case
           */
          input: string;
          /**
           * Expected output for this test case
           */
          expectedOutput: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Different programming language versions of this challenge
   */
  codeVersions?:
    | {
        /**
         * Programming language for this version
         */
        language: string;
        /**
         * Initial code provided to users for this language
         */
        initialCode: string;
        /**
         * Test cases for validating solutions in this language
         */
        testCases?:
          | {
              /**
               * Input data for the test case
               */
              input: string;
              /**
               * Expected output for this test case
               */
              expectedOutput: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  /**
   * The content of the comment
   */
  content: string;
  /**
   * The ID of the user who created the comment
   */
  authorId: string;
  /**
   * The votes for this comment
   */
  votes?:
    | {
        /**
         * The ID of the user who voted
         */
        userId: string;
        /**
         * The type of vote
         */
        vote: 'upvote' | 'downvote';
        id?: string | null;
      }[]
    | null;
  /**
   * Whether this comment is a reply
   */
  isReply?: boolean | null;
  /**
   * Replies to this comment
   */
  replies?: (number | Comment)[] | null;
  /**
   * Reports made against this comment
   */
  reports?:
    | {
        userId: string;
        reason: string;
        details?: string | null;
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-solutions".
 */
export interface UserSolution {
  id: number;
  /**
   * The title of the solution
   */
  title: string;
  /**
   * A brief description of the solution
   */
  description: string;
  /**
   * The challenge this solution is for
   */
  challenge: number | Challenge;
  /**
   * The ID of the user who created the solution
   */
  authorId: string;
  /**
   * The votes for this solution
   */
  votes?:
    | {
        /**
         * The type of vote
         */
        status: 'upvote' | 'downvote';
        /**
         * The ID of the user who voted
         */
        authorId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Number of times this solution has been viewed
   */
  views?: number | null;
  /**
   * Tags associated with this solution
   */
  tags?: (number | Tag)[] | null;
  /**
   * The main content of the solution
   */
  content: string;
  /**
   * Comments on this solution
   */
  comments?: (number | Comment)[] | null;
  /**
   * Reports made against this solution
   */
  reports?:
    | {
        userId: string;
        reason: string;
        details?: string | null;
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeProgression".
 */
export interface UserChallengeProgression {
  id: number;
  /**
   * ID of the user
   */
  userId: string;
  /**
   * Related challenge
   */
  challenge: number | Challenge;
  /**
   * Whether the user has liked this challenge
   */
  hasLiked?: boolean | null;
  /**
   * Whether the user has disliked this challenge
   */
  hasDisliked?: boolean | null;
  /**
   * User rating for this challenge (1-5)
   */
  rating?: number | null;
  /**
   * Current completion status of the challenge
   */
  completionStatus: 'not_started' | 'in_progress' | 'completed';
  /**
   * Whether the solution has been unlocked by the user
   */
  isSolutionUnlocked?: boolean | null;
  /**
   * Code submissions for this challenge
   */
  code?:
    | {
        /**
         * Programming language of the code
         */
        language: string;
        /**
         * The actual code content
         */
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-submissions".
 */
export interface ChallengeSubmission {
  id: number;
  /**
   * Type of submission result
   */
  submissionType: 'accepted' | 'runtimeError' | 'wrongAnswer' | 'timeLimitExceeded';
  /**
   * The challenge this submission is for
   */
  challenge: number | Challenge;
  /**
   * The user who made this submission
   */
  authorId: string;
  /**
   * Number of test cases passed
   */
  testsPassed: number;
  /**
   * Total number of test cases
   */
  testsTotal: number;
  code: {
    /**
     * Programming language used for the submission
     */
    language: string;
    /**
     * Source code of the submission
     */
    content: string;
  };
  /**
   * Error message for runtime error submissions
   */
  error?: string | null;
  /**
   * Last expected outputs before the error occurred
   */
  lastExpectedOutput?:
    | {
        output?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Input that caused the wrong answer
   */
  input?: string | null;
  /**
   * Actual output produced by the submission
   */
  output?: string | null;
  /**
   * Expected output for the given input
   */
  expectedOutput?: string | null;
  /**
   * When this submission was made
   */
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  userId: string;
  content: string;
  importance: 'high' | 'medium' | 'low';
  type: 'system' | 'challenge' | 'achievement' | 'social';
  isRead?: boolean | null;
  /**
   * Optional URL or route for the notification action
   */
  actionUrl?: string | null;
  /**
   * Optional expiration date for the notification
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  skillConcepts?: (number | SkillConcept)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-concepts".
 */
export interface SkillConcept {
  id: number;
  baseConcept: number | BaseConcept;
  skill: number | Skill;
  difficulty?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "base-concepts".
 */
export interface BaseConcept {
  id: number;
  name: string;
  description: string;
  requiredBaseConcepts?: (number | BaseConcept)[] | null;
  nextBaseConcepts?: (number | BaseConcept)[] | null;
  similarBaseConcepts?: (number | BaseConcept)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-categories".
 */
export interface ChallengeCategory {
  id: number;
  /**
   * The name of the challenge category
   */
  name: string;
  /**
   * A brief summary of the category that appears at the top of the page
   */
  summary?: string | null;
  /**
   * A detailed description of what this category covers
   */
  description: string;
  /**
   * URL-friendly identifier for this category
   */
  slug: string;
  /**
   * Whether this category is locked and unavailable to users
   */
  isLocked?: boolean | null;
  /**
   * Different parts/sections within this category
   */
  parts?:
    | {
        /**
         * Name of this part/section
         */
        name: string;
        /**
         * Description of what this part covers
         */
        description?: string | null;
        /**
         * Sequence of challenges in this part
         */
        challenges: (number | Challenge)[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User following relationships and blocked users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-following-informations".
 */
export interface UserFollowingInformation {
  id: number;
  userId: string;
  followers?:
    | {
        id: string | null;
      }[]
    | null;
  following?:
    | {
        id: string | null;
      }[]
    | null;
  blockedUsers?:
    | {
        id: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tutorials';
        value: number | Tutorial;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'support-settings';
        value: number | SupportSetting;
      } | null)
    | ({
        relationTo: 'user-informations';
        value: number | UserInformation;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'user-gamification';
        value: number | UserGamification;
      } | null)
    | ({
        relationTo: 'user-inventory';
        value: number | UserInventory;
      } | null)
    | ({
        relationTo: 'user-currency';
        value: number | UserCurrency;
      } | null)
    | ({
        relationTo: 'quests';
        value: number | Quest;
      } | null)
    | ({
        relationTo: 'user-quests';
        value: number | UserQuest;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'user-achievements';
        value: number | UserAchievement;
      } | null)
    | ({
        relationTo: 'challenges';
        value: number | Challenge;
      } | null)
    | ({
        relationTo: 'userChallengeProgression';
        value: number | UserChallengeProgression;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'user-solutions';
        value: number | UserSolution;
      } | null)
    | ({
        relationTo: 'challenge-submissions';
        value: number | ChallengeSubmission;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'base-concepts';
        value: number | BaseConcept;
      } | null)
    | ({
        relationTo: 'skill-concepts';
        value: number | SkillConcept;
      } | null)
    | ({
        relationTo: 'challenge-categories';
        value: number | ChallengeCategory;
      } | null)
    | ({
        relationTo: 'user-following-informations';
        value: number | UserFollowingInformation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  articleStatus?: T;
  difficultyLevel?: T;
  author?: T;
  tags?: T;
  analytics?:
    | T
    | {
        views?: T;
        uniqueViews?: T;
        recommendationClicks?: T;
        averageTimeSpent?: T;
        bounceRate?: T;
        ratingCount?: T;
        ratingSum?: T;
      };
  translations?:
    | T
    | {
        language?: T;
        title?: T;
        subtitle?: T;
        content?: T;
        translator?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?:
                | T
                | {
                    keyword?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  relatedArticles?: T;
  prerequisites?: T;
  nextSteps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials_select".
 */
export interface TutorialsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  tutorialStatus?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        articles?: T;
        id?: T;
      };
  exampleSections?:
    | T
    | {
        title?: T;
        articles?: T;
        id?: T;
      };
  referenceSections?:
    | T
    | {
        title?: T;
        description?: T;
        articles?: T;
        id?: T;
      };
  translations?:
    | T
    | {
        language?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  usageCount?: T;
  creatorId?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  message?: T;
  articleSlug?: T;
  tutorialSlug?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-settings_select".
 */
export interface SupportSettingsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  maintenanceMessage?: T;
  offlineMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-informations_select".
 */
export interface UserInformationsSelect<T extends boolean = true> {
  userId?: T;
  name?: T;
  avatar?: T;
  initials?: T;
  role?: T;
  permissions?: T;
  preferences?:
    | T
    | {
        notifications?:
          | T
          | {
              friends?: T;
            };
        emails?:
          | T
          | {
              marketing?: T;
              affiliates?: T;
            };
        theme?: T;
      };
  customerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  code?: T;
  category?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-gamification_select".
 */
export interface UserGamificationSelect<T extends boolean = true> {
  userId?: T;
  currentLevel?: T;
  currentExperience?: T;
  totalExperience?: T;
  lastLevelUpDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-inventory_select".
 */
export interface UserInventorySelect<T extends boolean = true> {
  userId?: T;
  items?:
    | T
    | {
        itemEntries?:
          | T
          | {
              itemType?: T;
              itemVariant?: T;
              quantity?: T;
              id?: T;
            };
      };
  itemCount?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-currency_select".
 */
export interface UserCurrencySelect<T extends boolean = true> {
  userId?: T;
  coins?: T;
  transactionHistory?:
    | T
    | {
        timestamp?: T;
        type?: T;
        amount?: T;
        source?: T;
        details?: T;
        id?: T;
      };
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests_select".
 */
export interface QuestsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  difficulty?: T;
  value?: T;
  experience?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-quests_select".
 */
export interface UserQuestsSelect<T extends boolean = true> {
  userId?: T;
  quest?: T;
  currentProgression?: T;
  isCompleted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  icon?: T;
  maxTier?: T;
  tiers?:
    | T
    | {
        name?: T;
        description?: T;
        threshold?: T;
        rewardCoins?: T;
        rewardXp?: T;
        id?: T;
      };
  isActive?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-achievements_select".
 */
export interface UserAchievementsSelect<T extends boolean = true> {
  userId?: T;
  achievements?:
    | T
    | {
        achievementId?: T;
        currentValue?: T;
        currentTier?: T;
        unlockedTiers?:
          | T
          | {
              tier?: T;
              unlockedAt?: T;
              rewardClaimed?: T;
              id?: T;
            };
        lastUpdated?: T;
        id?: T;
      };
  totalAchievements?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  difficulty?: T;
  baseExperience?: T;
  ratings?:
    | T
    | {
        total?: T;
        count?: T;
        average?: T;
      };
  concepts?:
    | T
    | {
        concept?: T;
        id?: T;
      };
  engagement?:
    | T
    | {
        likes?: T;
        dislikes?: T;
      };
  description?:
    | T
    | {
        statement?: T;
        submissionStats?:
          | T
          | {
              acceptedSolutions?: T;
              failedSolutions?: T;
              totalSubmissions?: T;
              acceptanceRate?: T;
            };
        hints?:
          | T
          | {
              content?: T;
              id?: T;
            };
        similarChallenges?:
          | T
          | {
              challenge?: T;
              id?: T;
            };
        comments?: T;
      };
  officialSolution?:
    | T
    | {
        statement?: T;
        comments?: T;
      };
  userSolutions?: T;
  submissions?:
    | T
    | {
        submissionType?: T;
        authorId?: T;
        testsPassed?: T;
        testsTotal?: T;
        createdAt?: T;
        error?: T;
        input?: T;
        output?: T;
        expectedOutput?: T;
        lastExpectedOutput?:
          | T
          | {
              param?: T;
              value?: T;
              id?: T;
            };
        code?:
          | T
          | {
              language?: T;
              content?: T;
            };
        id?: T;
      };
  code?:
    | T
    | {
        language?: T;
        initialCode?: T;
        testCases?:
          | T
          | {
              input?: T;
              expectedOutput?: T;
              id?: T;
            };
      };
  codeVersions?:
    | T
    | {
        language?: T;
        initialCode?: T;
        testCases?:
          | T
          | {
              input?: T;
              expectedOutput?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userChallengeProgression_select".
 */
export interface UserChallengeProgressionSelect<T extends boolean = true> {
  userId?: T;
  challenge?: T;
  hasLiked?: T;
  hasDisliked?: T;
  rating?: T;
  completionStatus?: T;
  isSolutionUnlocked?: T;
  code?:
    | T
    | {
        language?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  content?: T;
  authorId?: T;
  votes?:
    | T
    | {
        userId?: T;
        vote?: T;
        id?: T;
      };
  isReply?: T;
  replies?: T;
  reports?:
    | T
    | {
        userId?: T;
        reason?: T;
        details?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-solutions_select".
 */
export interface UserSolutionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  challenge?: T;
  authorId?: T;
  votes?:
    | T
    | {
        status?: T;
        authorId?: T;
        id?: T;
      };
  views?: T;
  tags?: T;
  content?: T;
  comments?: T;
  reports?:
    | T
    | {
        userId?: T;
        reason?: T;
        details?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-submissions_select".
 */
export interface ChallengeSubmissionsSelect<T extends boolean = true> {
  submissionType?: T;
  challenge?: T;
  authorId?: T;
  testsPassed?: T;
  testsTotal?: T;
  code?:
    | T
    | {
        language?: T;
        content?: T;
      };
  error?: T;
  lastExpectedOutput?:
    | T
    | {
        output?: T;
        id?: T;
      };
  input?: T;
  output?: T;
  expectedOutput?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  userId?: T;
  content?: T;
  importance?: T;
  type?: T;
  isRead?: T;
  actionUrl?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  skillConcepts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "base-concepts_select".
 */
export interface BaseConceptsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  requiredBaseConcepts?: T;
  nextBaseConcepts?: T;
  similarBaseConcepts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-concepts_select".
 */
export interface SkillConceptsSelect<T extends boolean = true> {
  baseConcept?: T;
  skill?: T;
  difficulty?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-categories_select".
 */
export interface ChallengeCategoriesSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  description?: T;
  slug?: T;
  isLocked?: T;
  parts?:
    | T
    | {
        name?: T;
        description?: T;
        challenges?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-following-informations_select".
 */
export interface UserFollowingInformationsSelect<T extends boolean = true> {
  userId?: T;
  followers?:
    | T
    | {
        id?: T;
      };
  following?:
    | T
    | {
        id?: T;
      };
  blockedUsers?:
    | T
    | {
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}