/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    tutorials: Tutorial;
    tags: Tag;
    feedbacks: Feedback;
    'support-settings': SupportSetting;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    tutorials: TutorialsSelect<false> | TutorialsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    feedbacks: FeedbacksSelect<false> | FeedbacksSelect<true>;
    'support-settings': SupportSettingsSelect<false> | SupportSettingsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-friendly identifier for this article. Will be used in the URL.
   */
  slug: string;
  subtitle?: string | null;
  content: string;
  /**
   * Information for search engine optimization (SEO) of the article in the main language (English)
   */
  seo?: {
    /**
     * Optimized title for search engines (if different from the main title)
     */
    title?: string | null;
    /**
     * Short description for search results (150-160 characters recommended)
     */
    description?: string | null;
    /**
     * Relevant keywords for SEO
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Article visibility (independent from the draft/publish system)
   */
  articleStatus: 'active' | 'archived';
  /**
   * Difficulty level of the article
   */
  difficultyLevel: 'beginner' | 'intermediate' | 'advanced';
  author: number | User;
  /**
   * Concepts related to this article (e.g., "python", "object-oriented")
   */
  tags?: (number | Tag)[] | null;
  /**
   * Engagement metrics for this article (normally updated automatically)
   */
  analytics?: {
    /**
     * Total number of article views
     */
    views?: number | null;
    /**
     * Number of distinct visitors who viewed the article
     */
    uniqueViews?: number | null;
    /**
     * Number of times the article was viewed from a recommendation
     */
    recommendationClicks?: number | null;
    /**
     * Average time spent on the article in seconds
     */
    averageTimeSpent?: number | null;
    /**
     * Percentage of users who leave after viewing only this article
     */
    bounceRate?: number | null;
    /**
     * Total number of ratings received for this article
     */
    ratingCount?: number | null;
    /**
     * Sum of all ratings (scale of 1 to 5) - allows calculating the average
     */
    ratingSum?: number | null;
  };
  /**
   * Add translations for this article (the default language is English)
   */
  translations?:
    | {
        language: 'fr' | 'es';
        title: string;
        subtitle?: string | null;
        content: string;
        translator?: (number | null) | User;
        /**
         * Information for search engine optimization (SEO) of this translation
         */
        seo?: {
          /**
           * Optimized title for search engines (if different from the translated title)
           */
          title?: string | null;
          /**
           * Short description for search results (150-160 characters recommended)
           */
          description?: string | null;
          /**
           * Relevant keywords for SEO in this language
           */
          keywords?:
            | {
                keyword?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Select articles that are related to this article
   */
  relatedArticles?: (number | Article)[] | null;
  /**
   * Articles that should be read before this one
   */
  prerequisites?: (number | Article)[] | null;
  /**
   * Recommended articles to read after this one
   */
  nextSteps?: (number | Article)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials".
 */
export interface Tutorial {
  id: number;
  title: string;
  description?: string | null;
  /**
   * Tutorial visibility (independent from the draft/publish system)
   */
  tutorialStatus: 'active' | 'archived';
  /**
   * Sections of the tutorial, each containing a list of articles
   */
  sections: {
    title: string;
    description?: string | null;
    /**
     * Articles included in this section, in display order
     */
    articles: (number | Article)[];
    id?: string | null;
  }[];
  /**
   * Example sections for this tutorial, each grouping similar articles
   */
  exampleSections?:
    | {
        title: string;
        /**
         * Example articles included in this section
         */
        articles: (number | Article)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Reference article sections for this tutorial, organized by theme or category
   */
  referenceSections?:
    | {
        title: string;
        description?: string | null;
        /**
         * Reference articles included in this section
         */
        articles: (number | Article)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Add translations for the tutorial title (the default language is English)
   */
  translations?:
    | {
        language: 'fr' | 'es';
        title: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks".
 */
export interface Feedback {
  id: number;
  message: string;
  /**
   * The slug of the article where the feedback was submitted
   */
  articleSlug?: string | null;
  /**
   * The slug of the tutorial where the feedback was submitted
   */
  tutorialSlug?: string | null;
  /**
   * IP address of the user who submitted the feedback (for rate limiting)
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-settings".
 */
export interface SupportSetting {
  id: number;
  /**
   * Name of the settings (should be "Support Settings")
   */
  name: string;
  /**
   * Current status of the support system
   */
  status: 'online' | 'maintenance' | 'offline';
  /**
   * Message to display when support is in maintenance mode
   */
  maintenanceMessage?: string | null;
  /**
   * Message to display when support is offline
   */
  offlineMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'tutorials';
        value: number | Tutorial;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'feedbacks';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'support-settings';
        value: number | SupportSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  articleStatus?: T;
  difficultyLevel?: T;
  author?: T;
  tags?: T;
  analytics?:
    | T
    | {
        views?: T;
        uniqueViews?: T;
        recommendationClicks?: T;
        averageTimeSpent?: T;
        bounceRate?: T;
        ratingCount?: T;
        ratingSum?: T;
      };
  translations?:
    | T
    | {
        language?: T;
        title?: T;
        subtitle?: T;
        content?: T;
        translator?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?:
                | T
                | {
                    keyword?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  relatedArticles?: T;
  prerequisites?: T;
  nextSteps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials_select".
 */
export interface TutorialsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  tutorialStatus?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        articles?: T;
        id?: T;
      };
  exampleSections?:
    | T
    | {
        title?: T;
        articles?: T;
        id?: T;
      };
  referenceSections?:
    | T
    | {
        title?: T;
        description?: T;
        articles?: T;
        id?: T;
      };
  translations?:
    | T
    | {
        language?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedbacks_select".
 */
export interface FeedbacksSelect<T extends boolean = true> {
  message?: T;
  articleSlug?: T;
  tutorialSlug?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-settings_select".
 */
export interface SupportSettingsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  maintenanceMessage?: T;
  offlineMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}